var nShikigami = {
			name: [
				"Chouchin Obake", 
				"Chouchin Kozou", 
				"Akajita", 
				"Hakaarashi no Rei", 
				"Kiseirei", 
				"Karakasa Kozou", 
				"Amanojaku Midori", 
				"Amanojaku Aka", 
				"Amanojaku Ki", 
				"Amanojaku Ao", 
				"Hokigami", 
				"Norikabe",
				"Hắc Báo",
				"Kyonshi Inu"
			],
			tags: [
				"Chouchin Obake", 
				"Chouchin Kozou", 
				"Akajita", 
				"Hakaarashi no Rei", 
				"Kiseirei", 
				"Karakasa Kozou", 
				"Amanojaku Midori", 
				"Amanojaku Aka, Quỷ đỏ", 
				"Amanojaku Ki, manh mối: trống", 
				"Amanojaku Ao, Con diều", 
				"Hokigami", 
				"Norikabe, Tường đá",
				"Hắc Báo",
				"Kyonshi Inu,cho, chó"
			],
			tips: [
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"Quỷ đỏ",
				"manh mối: trống",
				"Con diều",
				"",
				"Tường đá",
				"",
				""
			],
			images: [
				"<img src='images/ChouchinObake.png'>", 
				"<img src='images/ChouchinKozou.png'>", 
				"<img src='images/Akajita.png'>", 
				"<img src='images/HakaarashinoRei.png'>", 
				"<img src='images/Kiseirei.png'>", 
				"<img src='images/KarakasaKozou.png'>", 
				"<img src='images/AmanojakuMidori.png'>", 
				"<img src='images/AmanojakuAka.png'>", 
				"<img src='images/AmanojakuKi.png'>", 
				"<img src='images/AmanojakuAo.png'>", 
				"<img src='images/Hokigami.png'>", 
				"<img src='images/Norikabe.png'>",
				"<img src='images/hacbao.png'>", 
				"<img src='images/KyonshiInu.png'>"
			],
			locations:[ 
				"Chương 1 - Amanojaku Ao đầu tiên có 2 (ải Thường), Chouchin Kozou thứ hai có 2 (ải Khó);<br> Chương 2 - Hakaarashi no Rei thứ hai có 2, Kiseirei đầu tiên có 2;<br> Chương 3 - Akashita đầu tiên có 2, Heiyo thứ hai có 2;<br> Chương 5 - Boss Kamikui có 1;<br> Chương 6 - cả 2 Chouchin Obake đều có 1;<br> Chương 7 - Kappa thứ hai có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 9 - Chouchin Kozou thứ nhất có 3, Chouchin Kozou thứ hai có 1, Boss Mouba có 1;<br> Chương 13 - Boss Kubinashi có 1;<br> Chương 17 - Boss Arakawa no Aruji có 1;<br> Kappa - Tầng 3 có 2;<br> Umibouzu - Tầng 1 có 3",
				"Chương 1 - Amanojaku Ao thứ hai có 2, cả 2 Chouchin Kozou có 1;<br> Chương 3 - Akashita thứ nhất có 1, Heiyo thứ nhất có 1 (ải Khó có 2), Heiyo thứ hai có 1;<br> Chương 7 - cả 3 Chouchin Kozou đều có 1;<br> Chương 8 - Boss Momo có 2;<br> Chương 9 - cả 2 Chouchin Kozou đều có 1;<br> Chương 12 - Doujo thứ nhất có 2;<br> Chương 15 - cả 3 Chouchin Kozou đều có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Gaki có 3, Futakuchi có 4, Kuro Mujou có 3, và Umibozu có 4;<br> Kappa - Tầng 1/2 có 3;<br> Ame Onna - Tầng 1/2 có 3;<br> Kamaitachi - Tầng 1 có 3;",
				"Chương 3 - Akashita thứ nhất có 1, Akashita thứ hai có 1;<br> Chương 10 - Satori thứ hai có 1;<br> Chương 15 - Tất cả quái đều có 1 trừ Boss;<br> <span class='redText'>[Nên đánh]</span> Chương 16 - Akashita thứ nhất có 1, Akashita thứ hai có 2, Akashita thứ ba có 1;<br> Momiji - Tầng 6 và 7 có 1;<br> Kappa - Tầng 3 có 1;<br> Ame Onna - Tầng 4 đến 6 có 1;<br> Kamaitachi - Tầng 1 có 3;",
				"Chương 2 - Hokigami có 1, cả 2 Hakaarashi no Rei đều có 1, Kiseirei thứ hai có 2;<br> Chương 12 - cả 2 Doujo đều có 1;<br> Kappa - Tầng 1/2 có 1;<br> <span class='redText'>[Nên đánh]</span> Ame Onna - Tầng 1/2/3 có 3;<br> <span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 1 có 3;<br> Ubume - Tầng 4 có 3; ",
				"Chương 2 - Hokigami có 1, Hakaarashi no Rei thứ nhất có 2, cả 2 Kiseirei đều có 1;<br> Chương 3 - Boss Hououka có 3;<br> Chương 5 - cả 2 Kanko đều có 1;<br> Chương 7 - Boss Youko có 1;<br> Chương 11 - Hồn Samurai thứ nhất có 3;<br> Chương 12 - Boss Yuki Onna có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 16 - Cả 3 Akashita đều có 3;<br> ",
				"<span class='redText'>[Nên đánh]</span> Chương 4 - Hokigami thứ hai có 2 (ải Khó có 3), cả 2 Karakasa Kozou đều có 1, Amanojaku Aka đầu tiên có 1, Amanojaku Aka thứ hai có 2;<br> Chương 8 - cả 2 Karakasa Kozou có 1;<br> Chương 13 - cả 3 Karakasa Kozou có 1;<br> Yêu khí - Gaki có 1;<br> <span class='redText'>[Nên đánh]</span> Ame Onna - Tầng 1 đến 3 có 1, Tầng 4 đến 6 có 3;<br> ",
				"Chương 1 - cả 2 Amanojaku Ao có 1, Chouchin Kozou đầu tiên có 2;<br> Chương 2 - Boss Zashiki Warashi có 2;<br> Chương 5 - Kanko cuối cùng có 3;<br> <span class='redText'>[Nên đánh]</span> Chương 6 - cả 2 Amanojaku Ao có 3, Boss Kodokushi có 3;<br> Chương 8 - cả 2 Amanojaku Ao có 1;<br> Chương 13 - cả 3 Karakasa Kozou có 2;<br> Chương 15 - cả 3 Amanojaku Ao có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Shouzu có 8, Gaki có 6, Hone Onna có 6, Kyonshi Ani có 4, và Umibozu có 1;<br> Kappa - Tầng 6 có 1;<br> ",
				"Chương 4 - Karakasa Kozou đầu tiên có 3, Karakasa Kozou thứ hai có 1 (ải Thường), cả 2 Amanojaku Aka có 1;<br> Chương 5 - Nurikabe đầu tiên có 2, Nurikabe thứ hai có 3, cả 2 Hokigami có 1;<br> Chương 6 - cả 2 Kochosei có 2;<br> Chương 7 - Boss Youko có 2;<br> Chương 11 - cả 2 Hitotsume Kozou có 2;<br> <span class='redText'>[Nên đánh]</span> Chương 13 - cả 3 Gaki có 3, cả 3 Karakasa Kozou có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 14 - cả 3 Hokigami có 3;<br> Boss Yumekui có 3;<br> Chương 15 - cả 3 Amanojaku Ao có 2;<br> Ngự hồn - Tầng 1 có 2;<br> Yêu khí - Kuro Mujou, Hone Onna, Shouzu, và Kyonshi Ani có 1;<br> Umibozu có 2 Kappa - Tầng 6 có 1 <br>",
				"Umibouzu - Tầng 1 có 2; <br> Chương 3 - cả 2 Amanojaku Ki có 1, Akashita thứ hai có 1;<br> Chương 5 - Hokigami thứ hai có 2, Kanko đầu tiên có 2;<br> Chương 8 - cả 2 Amanojaku Ao có 2;<br> Chương 12 - Oguna đầu tiên có 1;<br> Ngự hồn - Tầng 1 có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Umibozu có 3, Shouzu có 2, và Kyonshi Ani có 1;<br> Momiji - Tầng 4 và 5 có 1;<br> Kappa - Tầng 5/6 có 1;<br> ",
				"Chương 2 - Boss Zashiki Warashi có 1; <br> Chương 5 - Boss Kamikui có 2; <br> Chương 6 - cả 2 Amanojaku Ao có 1; <br>Chương 8 - cả 2 Amanojaku Ao có 1, Boss Momo có 1; <br>Chương 10 - cả 2 Ushi no Kokumairi có 2; <br>Chương 11 - Boss Momiji có 2; <br>Ngự hồn - Tầng 1 có 1; <br>Yêu khí - Futakuchi có 3, Kyonshi Ani có 3, và Umibozu có 1; <br>Kappa - Tầng 6 có 1; <br><span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 2, 3 có 4 - Tầng 1, 4, 5, 6 có 3;<br>Ubume - Tâng 4 có 1;<br>",
				"Umibouzu - Tầng 1 có 3; <br> Chương 2 - Hokigami có 1;<br> Chương 3 - Amanojaku Ki đầu tiên có 2 (ải Khó có 1);<br> Chương 4 - cả 2 Hokigami có 1, Boss Ame Onna có 2;<br> Chương 5 - cả 2 Hokigami có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 6 - cả 2 Chouchin Obake có 3;<br> Chương 7 - Koi đầu tiên có 1, thứ hai có 3;<br> Chương 8 - cả 2 Momo có 1, Karakasa Kozou đầu tiên có 3, Karakasa Kozou thứ hai có 2, Boss Momo có 1;<br> Chương 9 - Tesso đầu tiên có 3, và Tesso thứ hai có 2;<br> Chương 12 - Umibozu đầu tiên có 1;<br> Chương 14 - cả 3 Hokigami có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Futakuchi có 4, Kuro Mujou có 3, Hone Onna có 4, và Kyonshi Ani có 2; <br> <span class='redText'>[Nên đánh]</span> Ubume - Tầng 1, 2, 3 có 3<br>",
				"Chương 3 - Amanojaku Ki đầu tiên có 1 (ải Khó có 2);<br> Chương 4 - Hokigami đầu tiên có 2, Hokigami thứ hai có 1 (ải Thường), Karakasa Kozou thứ hai có 2 (ải Khó có 3), Amanojaku Aka đầu tiên có 2 (ải Khó có 3);<br> Chương 5 - Nurikabe đầu tiên có 1 trong ải Thường (2 trong ải Khó), Nurikabe thứ hai có 1, Hokigami đầu tiên có 2;<br> Chương 6 - cả 2 Kochosei có 1;<br> Chương 7 - Kappa đầu tiên có 2, Boss Youko có 3;<br> Chương 8 - Momo đầu tiên có 2, Momo thứ hai có 3;<br> Chương 11 - Hitotsume Kozou đầu tiên có 1, Gaki đầu tiên có 1;<br> Chương 12 - Umibozu đầu tiên có 2, Umibozu thứ hai có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 14 - cả 3 Nurikabe có 6;<br> Ngự hồn - Tầng 1 có 1;<br> Yêu khí - Gaki có 1, Kuro Mujou có 4;<br> Momiji - Tầng 4 và 5 có 1; <br> Youtouchi - Tầng 4, 5 có 1;<br> Ubume - Tầng 1, 2, 3 có 1;<br>",
				"Chương 5 - Nurikabe đầu tiên có 1 trong ải Thường;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 4 có 3; ",
				"Chương 1 - Amanojaku Ao đầu tiên có 2 trong ải Khó;<br> <span class='redText'>[Nên đánh]</span> Chương 7 - cả 2 Chouchin Kozou đầu tiên có 3, Chouchin Kozou thứ ba có 1, Kappa cuối cùng có 2;"
			]
}
var rShikigami = {
	name: [
		"Sanbi no Kitsune",
		"Zashiki Warashi",
		"Koi",
		"Kyuinochi Neko",
		"Bakedanuki",
		"Kappa",
		"Oguna",
		"Doujo",
		"Gaki",
		"Kodokushi",
		"Karasu Tengu",
		"Kamigui",
		"Hồn Samurai",
		"Ame Onna",
		"Kyonshi Imouto",
		"Heiyo",
		"Ushi no Kokumairi",
		"Hitotsume Kozou",
		"Tesso",
		"Shouzu",
		"Kanko",
		"Yamausagagi",
		"Hotarugusa",
		"Kochosei",
		"Yamawaro",
		"Kubinashi",
		"Satori",
		"Jikigaeru"
	],
	tags: [
		"Sanbi no Kitsune",
		"Zashiki Warashi",
		"Koi",
		"Kyuinochi Neko",
		"Bakedanuki",
		"Kappa",
		"Oguna",
		"Doujo",
		"Gaki",
		"Kodokushi",
		"Karasu Tengu",
		"Kamigui",
		"Hồn Samurai",
		"Ame Onna",
		"Kyonshi Imouto",
		"Heiyo",
		"Ushi no Kokumairi",
		"Hitotsume Kozou",
		"Tesso",
		"Shouzu",
		"Kanko",
		"Yamausagagi",
		"Hotarugusa",
		"Kochosei",
		"Yamawaro",
		"Kubinashi",
		"Satori",
		"Jikigaeru"
	],
	tips: [
		"Cây anh đào<br>Màu đỏ<br>Hoa vũ",
		"Quỷ hỏa<br>Sừng",
		"Hồ nước<br>Bong bóng<br>Đuôi",
		"",
		"",
		"Hồ nước<br>Lá sen",
		"Cánh<br>Vũ Y<br>Hiến tế",
		"Cánh<br>Vũ Y<br>Bé gái nhỏ",
		"",
		"Độc<br>Trùng",
		"Naginata<br>Cánh<br>Mặt nạ",
		"",
		"",
		"Khóc<br>Mưa<br>Dù",
		"",
		"Bình giáp<br>Hóa đá",
		"Người rơm<br>Trù ểm",
		"Mắt<br>Phật thạch mắt<br>Sư thầy<br>Kinh kim cang",
		"Tài phú<br>May mắn",
		"Quạt<br>Nước<br>Vỏ sò<br>Đuôi",
		"",
		"",
		"Bồ công anh<br>Cắn",
		"Trống tay<br>Khả ái",
		"Thạch chùy<br>Quái lực",
		"",
		"",
		"Xúc xắc<br>Hũ<br>Gian lận",
	],
	images: [
		"<img src='images/SanbinoKitsune.png'>",
		"<img src='images/ZashikiWarashi.png'>",
		"<img src='images/Koi.png'>",
		"<img src='images/KyuinochiNeko.png'>",
		"<img src='images/Bakedanuki.png'>",
		"<img src='images/Kappa.png'>",
		"<img src='images/Oguna.png'>",
		"<img src='images/Doujo.png'>",
		"<img src='images/Gaki.png'>",
		"<img src='images/Kodokushi.png'>",
		"<img src='images/KarasuTengu.png'>",
		"<img src='images/Kamigui.png'>",
		"<img src='images/SamurainoRei.png'>",
		"<img src='images/AmeOnna.png'>",
		"<img src='images/KyonshiImouto.png'>",
		"<img src='images/Heiyo.png'>",
		"<img src='images/UshinoKokumairi.png'>",
		"<img src='images/HitotsumeKozou.png'>",
		"<img src='images/Tesso.png'>",
		"<img src='images/Shouzu.png'>",
		"<img src='images/Kanko.png'>",
		"<img src='images/Yamausagagi.png'>",
		"<img src='images/Hotarugusa.png'>",
		"<img src='images/Kochosei.png'>",
		"<img src='images/Yamawaro.png'>",
		"<img src='images/Kubinashi.png'>",
		"<img src='images/Satori.png'>",
		"<img src='images/Jikigaeru.png'>"
	],
	locations:[
		"Chương 6 - cả 2 Kochosei có 1;<br> Chương 18 - cả 3 Sanbi no Kitsune có 2;<br> Ngự hồn - Tầng 1 có 1, Nghiệp Nguyên Hỏa có 1;<br> Momiji - Tầng 3 có 1;<br> Ame Onna - Tầng 7 có 1;<br>",
		"Chương 2 - Boss Zashiki Warashi có 1;<br> Chương 7 - Boss Kanko có 2;<br> Chương 10 - Satori thứ hai có 2, Kairaishi thứ hai có 2;<br> Ngự hồn - Tầng 3 có 2 và tầng 6 có 1;<br> <span class='redText'>[Nên đánh]</span> Kết giới/PVP - rất dễ gặp;<br> Ame Onna - Tầng 1 có 3;<br> Kappa - Tầng 2/6 có 1;<br>",
		"Umibouzu - Tầng 4 có 4; <br><span class='redText'>[Nên đánh]</span> Chương 7 - Koi đầu tiên có 3, Koi thứ hai có 1, Kappa đầu tiên có 1, Chouchin Kozou cuối cùng có 2;<br> Ngự hồn - Tầng 2/3/9 có 1;<br> Kappa - Tầng 8/9 có 2, Tầng 10 có 1;<br> ",
		"Chương 1 - Boss Kyuumei Neko có 3;<br> Chương 15 - cả 3 Chouchin Kozou có 2, Boss Kyonshi Imoto có 3;<br> <span class='redText'>[Nên đánh]</span> Chương 18 - cả 3 Kyuumei Neko có 6, cả 3 Sanbi no Kitsune có 2;<br> Ame Onna - Tầng 1 đến 3 có 3;<br>",
		"Chương 10 - Satori đầu tiên có 3, Kairaishi đầu tiên có 2;<br> Chương 17 - cả 3 Tanuki có 1;<br> Ngự hồn - Tầng 9 có 1;<br> Momiji - Tầng 7 có 1;<br><span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 1, 2, 3 có 4 Tầng 4, 5, 6 có 3",
		"Umibouzu - Tầng 3 có 3, Tầng 5 có 5; <br> Chương 7 - cả 2 Kappa có 1;<br> Ngự hồn - Tầng 2 có 1;<br> Kappa - Tầng 1 đến 10 có 1;<br> Ame Onna - Tầng 8 có 5;<br> ",
		"Chương 12 - cả 2 Oguna có 1;<br> Ngự hồn - Tầng 4 có 1;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 1 có 3;<br> Ame Onna - Tầng 10 có 1;<br>",
		"<span class='redText'>[Nên đánh]</span> Chương 3 - Heiyo đầu tiên có 2 trong ải Thường (1 trong ải Khó), Akashita thứ hai có 2, Amanojaku Ki cuối cùng có 3;<br>Chương 11 - Boss Momiji có 1;<br> Chương 12 - Doujo đầu tiên có 1, Doujo thứ hai có 3, Oguna thứ hai có 1;<br> Ngự hồn - Tầng 2 có 2, Tầng 4 có 1;<br> Kappa - Tầng 1 có 1;<br> ",
		"Chương 9 - Boss Mouba có 3;<br> Chương 11 - Gaki đầu tiên có 1, Gaki thứ hai có 3;<br> Chương 13 - cả 3 Gaki có 1;<br> Chương 16 - cả 3 Gaki có 1;<br> Ngự hồn - Tầng 8 có 1;<br> Yêu khí - Gaki có 3;<br> <span class='redText'>[Nên đánh]</span> Momiji - Tầng 1 đến 3 có 4, Tầng 4 đến 10 có 3;<br> ",
		"Chương 6 - Boss Kodokushi có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 6 có 1;<br> Ame Onna - Tầng 7 đến 10 có 1;<br> Kamaitachi - Tầng 3 có 3;",
		"Chương 3 - cả 2 Akashita có 1;<br> Chương 9 - cả 2 Yamausagi có 1, Boss Mouba có 2;<br> <span class='redText'>[Nên đánh]</span> Chương 12 - Umibozu thứ hai có 2, cả 2 Oguna có 2 (tối đa có 4 do Oguna hồi sinh);<br> Chương 17 - cả 3 Karasu Tengu có 1;<br> Chương 18 - Boss Ootengu có 3;<br> Ngự hồn - Tầng 6 có 1;<br> Momiji - Tầng 4 có 2 và Tầng 9 có 1;<br> Kappa - Tầng 9 có 2;<br> Ame Onna - Tầng 7 đến 9 có 3, Tầng 10 có 5;<br> ",
		"Chương 5 - Boss Kamikui có 1;<br> Chương 10 - Boss Shuten Doji có 2;<br> Ngự hồn - Tầng 7 có 1;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 3 có 3;<br> ",
		"Chương 11 - cả 2 Hồn Samurai có 1;<br> Chương 12 - Boss Yuki Onna có 2;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 3 có 3;<br> <span class='redText'>[Nên đánh]</span> Ame Onna - Tầng 3 có 3;<br> ",
		"Chương 4 - Boss Ame Onna có 1;<br> Ngự hồn - Tầng 6 có 1;<br> Momiji - Tầng 6 có 2;<br> Ame Onna - Tầng 1 đến 10 có 1;<br> Kappa - Tầng 7/9 có 1;<br> <span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 3 có 3 <br>",
		"<span class='redText'>[Nên đánh]</span> Chương 12 - Boss Yuki Onna có 1, có thể dùng Kyonshi Ani để hồi sinh;<br> Chương 15 - Boss Kyonshi Imoto có 1;<br> Momiji - Tầng 2 có 1;<br> Kappa - Tầng 9 có 1;<br><span class='redText'>[Nên đánh]</span> Ubume - Tầng 4 đến 6 có 1",
		"Chương 3 - cả 2 Heiyo có 1;<br> Chương 10 - Boss Shuten Doji có 1;<br> Ngự hồn - Orochi Tầng 2 có 1, Nghiệp Nguyên Hỏa có 1;<br> Kết giới/PVP - Ít gặp;<br> Momiji - Tầng 4/5/8/10 có 1;<br> Kappa - Tầng 4 và 10 có 1;<br> <span class='redText'>[Nên đánh]</span> Ame Onna - Tầng 7 có 4;<br> ",
		"Chương 10 - cả 2 Ushi no Kokumairi có 1;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 4 có 2;<br> Ngự hồn - Tầng 5/7 có 1;<br> Momiji - Tầng 4 và 9 có 1;<br> Kappa - Tầng 4 có 2;<br> Ame Onna - Tầng 4 đến 6 có 1;<br>",
		"<span class='redText'>[Nên đánh]</span> Chương 11 - Hồn Samurai  thứ hai có 3, cả 2 Hitotsume Kozou có 1 trong ải Thường (2 trong ải Khó);<br> Ngự hồn - Tầng 1/5 có 1;<br> Momiji - Tầng 8 đến 10 có 1;<br> Kappa - Tầng 2 có 1;<br>",
		"Chương 9 - Tesso đầu tiên có 1, Tesso thứ hai có 2, Chouchin Kozou thứ hai có 2, Yamausagi thứ hai có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Quái Xu có 16;<br> Momiji - Tầng 5 có 2;<br> Ame Onna - Tầng 1 đến 3 có 1;<br> ",
		"Ngự hồn - Tầng 3/8/9/10 có 1, Nghiệp Nguyên Hỏa có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Shouzu có 3;<br> Kết giới/PVP - Dễ gặp;<br> Momiji - Tầng 6 đến 8 có 1, Tầng 9/10 có 2;<br> Kappa - Tầng 8/10 có 2;<br> Ame Onna - Tầng 8 có 1;<br> ",
		"Chương 5 - Kanko đầu tiên có 2, Kanko thứ hai có 1;<br> Chương 7 - cả 3 Chouchin Kozou có 1;<br> Chương 11 - Hitotsume Kozou thứ hai có 1, Gaki đầu tiên có 2, Gaki thứ hai có 1;<br> Ngự hồn - Tầng 8 có 1;<br> <span class='redText'>[Nên đánh]</span> Momiji - Tầng 1 đến 3 có 4, Tầng 4 đến 10 có 3;<br> Ame Onna - Tầng 9 có 5;<br> Kappa - Tầng 7 có 3;<br>",
		"<span class='redText'>[Nên đánh]</span> Chương 9 - Yamausagi đầu tiên có 4, Yamausagi thứ hai có 3;<br> Chương 13 - Boss Kubinashi có 1;<br> Chương 16 - cả 3 Gaki có 1;<br> Chương 17 - Boss Arakawa no Aruji có 1;<br> Ngự hồn - Tầng 7 có 1;<br> Kappa - Tầng 5 có 1;<br> PVP/Kết giới - Rất dể gặp;<br> ",
		"Ngự hồn - Tầng 2/9/10 có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Nghiệp Nguyên Hỏa - có 4;<br> Kappa - Tầng 4 và 9 có 1;<br> Ame Onna - Tầng 4/9 có 1, Tầng 10 có 3;<br> Kết giới/PvP - Ít gặp;<br>",
		"Chương 6 - cả 2 Kochosei có 1;<br> Chương 8 - Boss Momo có 2;<br> Ngự hồn - Tầng 3/8 có 1, Nghiệp Nguyên Hỏa có 1;<br> Ame Onna - Tầng 7 có 1;<br> Kappa - Tầng 5 có 2;<br><span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 2 có 3<br>",
		"Chương 8 - Karakasa Kozou thứ hai có 1;<br> Chương 16 - cả 3 Gaki có 2;<br> Ngự hồn - Tầng 1 có 1;<br> Momiji - Tầng 3 có 2;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 2 có 3;<br> ",
		"Chương 13 - Gaki cuối cùng có 1, Karakasa Kozou cuối cùng có 1, Boss Kubinashi có 1;<br> Momiji - Tầng 3 có 2;<br> Kappa - Tầng 7 có 3;<br> Ame Onna - Tầng 2 có 3;<br> ",
		"Chương 10 - cả 2 Satori có 1, cả 2 Kairaishi có 1;<br> Chương 11 - Boss Momiji có 2;<br> Ngự hồn - Tầng 10 có 1;<br> <span class='redText'>[Nên đánh]</span> Momiji - Tầng 1 có 3;<br> Kappa - Tầng 4 có 3;<br> Ame Onna - Tầng 4 đến 6 có 3;<br>, <span class='redText'>[Nên đánh]</span> Ubume - Tầng 1 đến 3 có 3<br>",
		"Chương 4 - Boss Ame Onna có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 3 có 1;<br> Kappa - Tầng 9 có 3;<br> Ame Onna - Tầng 10 có 5;<br> ",
	]
}
var srShikigami = {
	name: [
		"Momo no Sei",
		"Yuki Onna",
		"Shiro Mujou",
		"Kuro Mujou",
		"Mouba",
		"Inugami",
		"Hone Onna",
		"Momiji",
		"Kyonshi Ani",
		"Kairaishi",
		"Umibouzu",
		"Hangan",
		"Hououka",
		"Kyuuketsuhime",
		"Youko",
		"Yumekui",
		"Kamaitachi",
		"Sakura no Sei",
		"Ootengu",
		"Shuten Douji",
		"Lãnh chúa Arakawa",
		"Enma",
	],
	tags: [
		"Momo no Sei",
		"Yuki Onna",
		"Shiro Mujou",
		"Kuro Mujou",
		"Mouba",
		"Inugami",
		"Hone Onna",
		"Momiji",
		"Kyonshi Ani",
		"Kairaishi",
		"Umibouzu",
		"Hangan",
		"Hououka",
		"Kyuuketsuhime",
		"Youko",
		"Yumekui",
		"Kamaitachi",
		"Sakura no Sei",
		"Ootengu",
		"Shuten Douji",
		"Lãnh chúa Arakawa",
		"Enma",
	],
	tips: [
		"Hoa<br>Vũ",
		"",
		"Minh giới<br>Trắng<br>Đoạt mệnh",
		"Lưỡi hái<br>Đoản đao<br>Minh giới",
		"Bát<br>Cầm<br>Nha nha",
		"Gâu gâu<br>Thủ hộ",
		"Đầu lâu<br>Oán hận",
		"",
		"Nến<br>Quan tài",
		"Hình nhân<br>Thao túng",
		"Biển<br>Râu<br>Trượng",
		"",
		"",
		"Dơi<br>Máu",
		"Thư sinh<br>Mặt nạ",
		"Chuông<br>Ác mộng",
		"Chùy<br>Đinh ba<br>Rìu",
		"",
		"Lông vũ<br>Sáo<br>Quạt",
		"",
		"",
		"Mây<br>Minh giới",
	],
	images: [
		"<img src='images/MomonoSei.png'>",
		"<img src='images/YukiOnna.png'>",
		"<img src='images/ShiroMujou.png'>",
		"<img src='images/KuroMujou.png'>",
		"<img src='images/Mouba.png'>",
		"<img src='images/Inugami.png'>",
		"<img src='images/HoneOnna.png'>",
		"<img src='images/Momiji.png'>",
		"<img src='images/KyonshiAni.png'>",
		"<img src='images/Kairaishi.png'>",
		"<img src='images/Umibouzu.png'>",
		"<img src='images/Hangan.png'>",
		"<img src='images/Hououka.png'>",
		"<img src='images/Kyuuketsuhime.png'>",
		"<img src='images/Youko.png'>",
		"<img src='images/Yumekui.png'>",
		"<img src='images/Kamaitachi.png'>",
		"<img src='images/SakuranoSei.png'>",
		"<img src='images/Ootengu.png'>",
		"<img src='images/ShutenDouji.png'>",
		"<img src='images/AragawanoAruji.png'>",
		"<img src='images/Enma.png'>",
	],
	locations:[
		"Chương 8 - Boss Momo có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 3 có 1;<br> Momiji - Tầng 8 đến 10 có 1;<br> Kappa - Tầng 5 có 1, Tầng 10 có 2;<br> [Nên đánh] Khiêu chiến",
		"Chương 8 - cả 2 Sakura có 1;<br> <span class='redText'>[Nên đánh]</span> Chương 12 - cả 2 Doujo có 1, Boss Yuki Onna có 2;<br> Momiji - Tầng 6 có 1;<br>",
		"Chương 16 - Boss Hangan có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 4 có 1;<br> Kappa - Tầng 6 có 3;<br> Ame Onna - Tầng 9 có 2;<br> Kamaitachi - Tầng 1 có 1;",
		"Chương 16 - Boss Hangan có 1;<br> Ngự hồn - Tầng 4 có 1;<br> Yêu khí - Kuro Mujou có 3;<br> <span class='redText'>[Nên đánh]</span> Kappa - Tầng 6 có 3;<br> ",
		"Chương 9 - Boss Mouba có 2;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 5 có 2, Tầng 6 có 1;<br> Kappa - Tầng 5 có 1;<br> ",
		"<span class='redText'>[Nên đánh]</span> Chương 10 - Satori thứ hai có 1, Kairaishi thứ hai có 1;<br> Ngự hồn - Tầng 4 có 1;<br> Momiji - Tầng 8 đến 10 có 1;<br> ",
		"Chương 10 - Boss Shuten Doji có 2;<br> Chương 11 - Boss Momiji có 1;<br> Chương 13 - Boss Kubinashi có 1;<br> Chương 17 - Boss Arakawa no Aruji có 1;<br> Ngự hồn - Tầng 5 có 1, Tầng 6 có 2;<br> Yêu khí - Hone Onna có 3;<br> Momiji - Tầng 5 có 1;<br> <span class='redText'>[Nên đánh]</span> Ame Onna - Tầng 4 có 4",
		"Chương 11 - Boss Momiji có 2;<br> <span class='redText'>[Nên đánh]</span> Momiji - Tầng 1 đến 10 có 1;<br> Kappa - Tầng 5 có 1;<br>",
		"Chương 10 - Boss Shuten Doji có 1;<br> Chương 12 - Boss Yuki Onna có 2;<br> Ngự hồn - Tầng 5 có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Kyonshi Ani có 3;<br> Momiji - Tầng 2 có 1;<br> Ubume - Tầng 4 đến 6 có 1",
		"<span class='redText'>[Nên đánh]</span> Chương 10 - cả 2 Ushi no Kokumairi có 1, cả 2 Kairaishi có 1;<br> Ngự hồn - Tầng 5 có 1;<br> ",
		"Chương 12 - cả 2 Umibozu có 1;<br> Ngự hồn - Tầng 3 có 1;<br> <span class='redText'>[Nên đánh]</span> Yêu khí - Umibozu có 3;<br> Kappa - Tầng 8 có 3;<br> ",
		"Chương 16 - Boss Hangan có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 8 có 1;<br> Kappa - Tầng 7 có 1;<br> Ame Onna - Tầng 7 có 1;<br><span class='redText'>[Nên đánh]</span> Youtouchi - Tầng 4 có 3 <br>",
		"Chương 3 - Boss Hououga có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 7 có 1;<br> Kappa - Tầng 5 có 1;<br> ",
		"Ngự hồn - Tầng 2 có 1;<br> Kết giới/PVP - Ít gặp;<br> <span class='redText'>[Nên đánh]</span> Momiji - Tầng 7 có 2, Tầng 10 có 1;<br> Kappa - Tầng 8 có 2;<br> Ame Onna - Tầng 10 có 5;<br> ",
		"Chương 7 - Boss Youko có 2;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 2 có 1, Nghiệp Nguyên Hỏa có 1;<br> Kappa - Tầng 9/10 có 1;<br> ",
		"<span class='redText'>[Nên đánh]</span> Chương 14 - Nurikabe cuối cùng có 1, Boss Yumekui có 5;<br> Ngự hồn - Tầng 4 có 2, Tầng 9 có 1;<br> Kappa - Tầng 7 có 1;<br> ",
		"Ngự hồn - Tầng 5 có 1;<br> Kết giới/PVP - Thường gặp;<br> Kappa - Tầng 4 có 1;<br> <span class='redText'>[Nên đánh]</span> Khiêu chiến - Chương 18 Kamaitachi có 14;<br> ",
		"<span class='redText'>[Nên đánh]</span> Chương 8 - cả 2 Sakura có 1, Boss có 1;<br> Kappa - Tầng 5/10 có 1;<br>",
		"Chương 15 - Chouchin Kozou cuối cùng có 1;<br> Chương 18 - Sanbi no Kitsune đầu tiên có 1, Boss Ootengu có 1;<br> Ngự hồn - Tầng 4 có 1, Tầng 10 có 2;<br> <span class='redText'>[Nên đánh]</span> Kết giới/PVP - Thường gặp;<br> Kappa - Tầng 9 có 1;<br>Ubume - Tầng 4 có 1<br> ",
		"Chương 10 - Boss Shuten Doji có 2;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 7/10 có 1;<br> Kết giới/PVP - ít gặp;<br> Momiji - Tầng 7 đến 10 có 1;<br> ",
		"Chương 17 - Boss Arakawa no Aruji có 1;<br> <span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 7 có 2;<br> Kappa - Tầng 8 có 2;<br> ",
		"<span class='redText'>[Nên đánh]</span> Ngự hồn - Tầng 6 có 1;<br> Kappa - Tầng 9 có 1;<br>",
	]
}